before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: K9skrjyudSLP7uCZGTBGQNwnZbOm+4JoYhe01YDXn7UD9QeiP23eWh3ii/r0E1aVSZxBGzXMect8IrW3NM3cSCo51gm+L0A2DJIYZQ96gA0RZZG4DixLVTbL2XRCZkP8Nk0abLtFl1/kCSNqtnhBcASyZK6V/QW/O0cL8P/T84rffMa3tvMnaHg/8PD9zS/z+c0I0XBdCFO0f59Cw0aiLSbR35pFUZda0LIcXcKrDq91eR1UsfiVhhD4swRPba2prs8uoPqIeB2P7uTwwIXJgmn+v6ppEOYw7WbChjYfR2JUx5Vp4Si52CMc637BSvhzbBDMwiCn8AHPo0cznSb0Jv6kMKKytLaw2ie08BSAvqXL6oWEpHbRFN6XbIgnSTdQ/xBGowp64c1q5NEq110GCXkyZC/Rudph+x9WOdwqGwQO5J+aAh+9fzAkLe3TEGkjXsSPXZrnx8nLKHV5z1i5AX/Ec0LSZcH53ZNiuPJTkEnOd6jxZFhbMx8fKm4wHPCWZlfxlxTT6ZQ00SAlJ446qCRVlhXjOD29VjAKBiZeBq9O5aRIvrnDKdtBwdrInjHZrAIzPgrgi/F0tYu2bO1sfuOmT+F4/LhC/VOOb5qLoGEhC9jtp24kJZ4M9yOgf7VVusToDrxkvGsONCJ5BJ2L6R2ipw+loI8lervnTtJ2aUc= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
